### ISSUE TITLE
CloudFlare DNS resolution error for https://speedtracker.org/

### ISSUE THREAD

**Issue by webuniverseio** [speedtracker/speedtracker#11]
Hi, just in case if you don't know yet there is a DNS resolution error on CloudFlare side (see attached image) when you navigate to https://speedtracker.org/.
![image](https://cloud.githubusercontent.com/assets/911388/19607728/b10cb848-9799-11e6-90e8-e057e6bfaeba.png)

**Comment by webuniverseio** [comment]
Awesome, it is back up now.

**Comment by alexzaworski** [comment]
There's a DDOS attack on Dyn Managed DNS right now, a looooot of stuff is
down. I can't even access github.com-- this is likely related.
