### ISSUE TITLE
Slack Hook URL

### ISSUE THREAD

**Issue by enjikaka** [speedtracker/speedtracker#12]
speedtracker.yml says;
`hookUrl: "ENCRYPTED_SLACK_HOOK_URL"`

But on https://speedtracker.org/encrypt you cannot encrypt the URL.

What to do?

**Comment by eduardoboucas** [comment]
This is very odd. The encrypt tool seems to have reverted to an old version, for some reason.

I'll look into this and get it fixed asap. In the meantime, you can use this URL to encrypt your text, provided that you URI encode it.

https://speedtracker-toolkit-wunjwvrnzb.now.sh/encrypt/YOUR_KEY/URI_ENCODED_TEXT

Let me know if that works.

**Comment by enjikaka** [comment]
That worked :)

**Comment by eduardoboucas** [comment]
Fixed with https://github.com/speedtracker/speedtracker.org/pull/2.

Thanks!
