### ISSUE TITLE
Gettting 500 internal error

### ISSUE THREAD

**Issue by kakumar** [speedtracker/speedtracker#13]
Request has all the right details:- 
curl 'https://api.speedtracker.org/v1/test/kakumar/speedtracker/master/default?key=game2pipe' --2.0 -H 'Host: api.speedtracker.org' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0' -H 'Accept: _/_' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://speedtracker.org/test' -H 'Origin: https://speedtracker.org' -H 'Connection: keep-alive'

Response headers
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Date: Mon, 24 Oct 2016 19:43:26 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=d71a022572395d6facdab21947df82b941477338206; expires=Tue, 24-Oct-17 19:43:26 GMT; path=/; domain=.speedtracker.org; HttpOnly
Via: 1.1 vegur
X-Firefox-Spdy: h2
cf-ray: 2f6feaed0f1a22a0-LAX
x-powered-by: Express

**Comment by eduardoboucas** [comment]
Can you confirm you're using a private WPT instance? If so, can you email me at mail@eduardoboucas.com? I haven't had a chance to test SpeedTracker exhaustively on a private instance, so I could definitely use your help on this.

Thanks

**Comment by kakumar** [comment]
Yes private instance.. sent you an email with details

**Comment by eduardoboucas** [comment]
Fixed.
