### ISSUE TITLE
Doest seem to fetch any data

### ISSUE THREAD

**Issue by enjikaka** [speedtracker/speedtracker#14]
I've followed the docs and set up everything as described. Also triggered a run at the speedtracker website. Nothing is happening in though.

Github Pages link: https://tidal-engineering.github.io/speedtracker/
Repolink: https://github.com/tidal-engineering/speedtracker

**Comment by eduardoboucas** [comment]
https://github.com/tidal-engineering/speedtracker/blob/master/speedtracker.yml#L66

`wptUrl` should contain the URL to the WebPageTest server, and not the website to be tested. Unless you're running a private WPT instance, this will be https://www.webpagetest.org (you can just leave that field commented out, as that's used by default).

The URL of the site to be tested should be configured in the profile, which it seems to be: https://github.com/tidal-engineering/speedtracker/blob/master/_profiles/default.html#L28

**Comment by enjikaka** [comment]
@eduardoboucas wptUrl was commented out for the inital run. Then I changed to what's there now and triggered run number 2. Neither gave any result... :/

Will try commenting it out and running again

**Comment by jsilff** [comment]
I'm having the same issue. When I run the test, it says "success":true,"nextRun":1477477767358
Which is a some point in time?? But, alas, no data.

Love the idea and everything about this! Such a neat idea/implementation.

**Comment by eduardoboucas** [comment]
Is this still an issue?

**Comment by enjikaka** [comment]
@eduardoboucas Now i'm getting "Error unkown" on https://speedtracker.org/test when trying to run a test

**Comment by eduardoboucas** [comment]
@enjikaka I told you before that you're misusing the `wptUrl` field. You should leave that commented out if you wish to use the public instance.

**Comment by jsilff** [comment]
I'm getting the same unknown error as Jeremy when using
https://speedtracker.org/test

**Comment by enjikaka** [comment]
@eduardoboucas I now commented out `wptUrl` again. https://speedtracker.org/test still gives the same error.

**Comment by enjikaka** [comment]
Inspected the response when I click the "Run Test" button;

![](http://i.imgur.com/PoeII5X.png)

Is the wptKey not decrypted?

**Comment by eduardoboucas** [comment]
It is. Could you have encrypted the API key with the wrong key?

To be clear, on the [encrypt tool](https://speedtracker.org/encrypt) the first field should be your encryption key (in plain text), and the second field is your WPT API key.

**Comment by enjikaka** [comment]
@eduardoboucas I re-encrypted the WPT API key, got another string and after adding that to the config it worked! I'm pretty sure I typed my encryption password correctly; I do suspect that coping the WPT API key left out the `A.` on the start though.

I double click text I copy on Mac; clicking anything after the dot in this string `A.randomteXtandNum3er5ssszz` only selects the text after the dot :P

It didn't send alerts to Slack or mail though... I checked the strings and they were encrypted correctly. Any idea?

**Comment by eduardoboucas** [comment]
Glad it worked.

You have notifications configured, but you must define budget for at least one metric in your profile file, otherwise the alerts won't be triggered: https://github.com/tidal-engineering/speedtracker/blob/master/_profiles/default.html#L39-L47

See the example on the demo site: https://github.com/eduardoboucas/speedtracker/blob/master/_profiles/default.html

**Comment by enjikaka** [comment]
@eduardoboucas Didn't get it to work with that... :/ 
The budgets appear on https://tidal-engineering.github.io/speedtracker/ but I don't get any alerts.
(off topic for this issue though)

But thank you for your help. And thanks for a great project!

_(leaving the issue open so @jsilff can get help also, close it if you want to otherwise)_

**Comment by enjikaka** [comment]
After the second manual run after updating the perf budget I got alerts on both mail and Slack! Woho! 🎉

**Comment by eduardoboucas** [comment]
Happy days!

@jsilff please ensure you're encrypting your details correctly. I'm closing the issue, feel free to reopen if you're still experiencing problems after reviewing your setup.
