### ISSUE TITLE
"No url"

### ISSUE THREAD

**Issue by danyeah** [speedtracker/speedtracker#22]
Hello
Awesome project.

I set up everything as the doc said but i keep getting 
"NO_URL" error even tho it is present in my configuration:
https://github.com/danielhq/speedtracker/blob/master/_profiles/default.html

What am i missing?
Thanks

**Comment by eduardoboucas** [comment]
I suspect that's because the value you set for `location` isn't valid. If you're looking for a location in Europe, try one of the following:
- `ec2-eu-west-1-akamai`
- `Manchester_UK`
- `London_UK`
- `Brussels_BE`
- `Amsterdam_Godaddy`
- `Amsterdam_IISpeed_Loc`
- `Frankfurt_DE`
- `Frankfurt_DE_Ruxit`
- `ec2-eu-central-1-akamai`
- `Prague_CZ`
- `Poland_Loc`

Let me know if that works.

**Comment by danyeah** [comment]
Thanks for the answer. 
I used one of those location indicated  in this page: https://www.webpagetest.org/getLocations.php?f=html&k=A

Now i changed it to: "Frankfurt_DE:Chrome" 
and It's still not working.

**Comment by eduardoboucas** [comment]
Can you try removing the `:Chrome` part?

**Comment by danyeah** [comment]
> :(

Nope, not working, i changed it to the default:
  location: "Dulles:Chrome"

**Comment by eduardoboucas** [comment]
Does it still not work with the default location? You can try to remove the `location` property altogether.

SpeedTracker doesn't have a `NO_URL` error, which means this is coming from the WebPageTest API, hence the trial and error approach.

**Comment by danyeah** [comment]
Uhm I removed location, and i changed the domain (put www.google.com)
still getting "No url"
Might be something with the line formatting since Im modifying the files from the web and not with a text editor and pushing manually?

**Comment by danyeah** [comment]
I deleted the entire repo and did everything again.
Its working fine now.
Closing this issue.
Cheers :)

**Comment by QuentinAdt** [comment]
Hi
From my side, problem solved by removing the blank line before "---" in the /_profiles/default.html file :)
Best
