### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by danyeah** [speedtracker/speedtracker#23]
Already 2 Issues, hope I'm not bugging you :)

Anyway, after i setup everything its not displaying anything
https://danielhq.github.io/speedtracker/?period=day
Doc said i should allow a couple minutes to fetch and display data, 2 hours have passed and still nothing.

**Comment by webuniverseio** [comment]
A few days ago speedtracker stopped working for me (https://indigo-ui.github.io/speedtracker/default/?period=month). I tried to submit test manually from https://speedtracker.org/test, but I'm getting 503.

![image](https://cloud.githubusercontent.com/assets/911388/20488972/f621d378-afd6-11e6-8271-6bb856b18188.png)

I think that might be related. Thanks.

**Comment by eduardoboucas** [comment]
I'll do my best to have a look at this asap (@danielhq just realised it's been 13 days and I haven't got back to you, sorry!)

**Comment by jsilff** [comment]
I'm getting the same error (was working fine and then stopped 5 days ago). Console says: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by eduardoboucas** [comment]
Can you check now, please?

**Comment by jsilff** [comment]
Working again for me! Thank you!

**Comment by webuniverseio** [comment]
@eduardoboucas seems to be working now. Thank you!

**Comment by danyeah** [comment]
I get no errors whatsoever it just won't display any data.

**Comment by webuniverseio** [comment]
@danielhq can you check if manual tests work? Did you add speedtracker bot as collaborators to your repo?
@eduardoboucas I get way less scheduled commits: https://github.com/indigo-ui/speedtracker/commits/master Maybe something is wrong with the bot? Or maybe WPT started to refuse connections due to high traffic?

**Comment by eduardoboucas** [comment]
Not sure, will investigate.

**Comment by danyeah** [comment]
Manual tests work.
Ive added speedtracker bot as a collaborator when i forked the project, but is still
"Awaiting speedtracker-bot's response"

**Comment by eduardoboucas** [comment]
@danielhq Did you use the [connect tool](https://speedtracker.org/connect), as per the documentation? Also, what do you mean by "manual tests work"? If you're seeing that message it means the bot doesn't have access to your repository, so it can't be uploading any tests, manual or scheduled.

**Comment by danyeah** [comment]
Manual test i meant this:
https://speedtracker.org/test and it did work when i tried.

I dont remember if i connected it, but i think  i didnt because it is now a collaborator.
Must have missed some steps while doing and redoing, anyway i should wait some time to let it fetch some data.

Thanks

**Comment by danyeah** [comment]
Still no data.

**Comment by webuniverseio** [comment]
@danielhq wait for a day, it might start working if everything is setup properly.
@eduardoboucas by manual tests "working" i think @danielhq means that he can submit test successfully, but his dashboard doesn't have any data yet, so there might be some setup missing. It is also possible that bot is failing for him for some reason...

**Comment by eduardoboucas** [comment]
@danielhq try removing the `location` property from your profile to see if that helps (https://github.com/danielhq/speedtracker/blob/142713b991c450e9dfc124e7f88d3f20d637d196/_profiles/default.html#L26).

There's also the possibility that your encryption key or WPT key are not correct or have been encrypted incorrectly, which I have no way of checking for you.

**Comment by webuniverseio** [comment]
@eduardoboucas I guess if manual test succeeds than encryption and WPT key are correct.

**Comment by danyeah** [comment]
Ok I removed the "location" parameter.
Let's see

**Comment by eduardoboucas** [comment]
Closing, since [commits are showing](https://github.com/danielhq/speedtracker/commit/da9f8769905e2b7f511f641231df6ad746ef4241).
