### ISSUE TITLE
WPT_ERROR - possible reasons?

### ISSUE THREAD

**Issue by tomat** [speedtracker/speedtracker#24]
Getting this error when attempting to run a test via the API:

`curl -s https://api.speedtracker.org/v1/test/flm/speedtracker/master/devote_beta_blogpost?key=XXX
{"success":false,"error":{"code":"WPT_ERROR"}}`

Is there a way to get a more verbose error message?

Thanks for a really cool service btw :-)

**Comment by eduardoboucas** [comment]
Sorry, just seen this. Is it still an issue?

**Comment by tomat** [comment]
> Sorry, just seen this. Is it still an issue?

Not this specific case, it's working now.

Would be practical to get a more verbose error though, if at all possible.

**Comment by eduardoboucas** [comment]
Indeed. Getting better error reporting is my next big priority.

Will close this issue now, but feel free to reopen if you encounter any other problems.

Thanks!

**Comment by timuric** [comment]
Unfortunately I am also getting such error. Any tip what it can be? Thanks
