### ISSUE TITLE
Add JavaScript Linter

### ISSUE THREAD

**Issue by danielbayerlein** [speedtracker/speedtracker#30]
I think a style linter would be great. For example:
* http://eslint.org
  * https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
  * ...
* https://github.com/sindresorhus/xo
* ...

Do you prefer a style linter?

**Comment by eduardoboucas** [comment]
I agree! I like ESlint. What are your thoughts?

**Comment by danielbayerlein** [comment]
I also prefer ESLint. In my projects I use ESLint with the [airbnb configuration](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

**Comment by danielbayerlein** [comment]
I can take the issue if you want...

**Comment by eduardoboucas** [comment]
@danielbayerlein that would be great!

We could integrate with [Travis](https://travis-ci.org/) to do linting of new PRs?

**Comment by danielbayerlein** [comment]
> We could integrate with Travis to do linting of new PRs?

Sure 👍

**Comment by ghost** [comment]
KISS on that linter, please. ESLint brings with it a world of noise and some particularly distracting configuration likely to lead to pedantic conversation in PRs. I would only recommend ESLint for an organization with a highly cohesive team of 6-12+ individuals.

My suggestion: http://standardjs.com/

---

> We could integrate with Travis to do linting of new PRs?

Yes. And use a pre-commit hook to stop the commit before it results in bad code entering the system and hitting CI. Hooks are relatively easy to set-up. Here's [an example](https://github.com/jhabdas/fetch-inject/blob/d080c981f8b6b6cbf843fe35c71bc947344884b8/package.json#L52-L54) using `ghooks`.

**Comment by ghost** [comment]
If we can settle on Standard I'll get a PR together for linting with pre-commit hook and CI integration.

**Comment by eduardoboucas** [comment]
I'm quite happy with using Standard.

**Comment by danielbayerlein** [comment]
@jhabdas I would also put on `JavaScript Standard Style` at this time.

**Comment by ghost** [comment]
@eduardoboucas preferences? https://standardjs.com/#is-there-a-readme-badge

**Comment by eduardoboucas** [comment]
I'd say the small one, but happy to go with your choice. :)

**Comment by ghost** [comment]
@eduardoboucas Re the small one. As soon as we add badge two is what I was thinking, for consistency. Until then I felt the big one was prettier and stood out more. 💄 really, but it hit my heart when I thought of the old badges we used to use on the Web.
