### ISSUE TITLE
getVideoFrameURL is hard-coded to use https://www.webpagetest.org as the domain

### ISSUE THREAD

**Issue by rsahlstrom** [speedtracker/speedtracker#34]
We're using a private instance of webpagetest and not publishing our results publicly. As a result, the images are not pushed up to https://www.webpagetest.org. However, they are published on our private ec2 instance. 

Looking at getVideoFrameURL though, it's hard-coded to always try to load the images form webpagetest.org. https://github.com/speedtracker/speedtracker/blob/2c5b717e644fbc1e02c781b4ee2bc1d9b3434d3b/app/Utils.js#L44

Is it possible to instead use the value in wptUrl instead as the base URL for getVideoFrameURL?

**Comment by eduardoboucas** [comment]
Absolutely. I'll look into this.

**Comment by eduardoboucas** [comment]
This is a bit more complex than what I had anticipated. The value for `wptUrl` is configured in the main configuration file (`speedtracker.yml`), which is never accessed by the dashboard — it doesn't even know how to locate or read this file.

One possible solution for this would be to move this value to the profile files, which are accessible by the dashboard. This would have the added benefit of allowing different profiles to use different WPT instances, which is a feature that was suggested in the past (ping @iamnmtd).

Would you be against this?

**Comment by rsahlstrom** [comment]
That'd be fine with me. Thanks for figuring this out.

**Comment by eduardoboucas** [comment]
@janiv Could you help me test this?

To see if this works, you'll need to do two things:

- **Update your dashboard**: I deployed some changes to [my fork](https://github.com/eduardoboucas/speedtracker) of the SpeedTracker dashboard. You can get them by creating a pull request from my fork to yours. You'll also need to add your WPT URL to your profile, as shown [here](https://github.com/eduardoboucas/speedtracker/blob/master/_profiles/default.html#L30-L36).

- **Request a test using the staging API**: I deployed a new version of the API to the staging instance, which lives at `dev.speedtracker.org`, as opposed to the live one at `api.speedtracker.org`. You'd need to request a test using this version and it'd need to be done using a GET or POST request and not using the UI at speedtracker.org. You can see how [here](https://speedtracker.org/docs#run).

I don't have a private instance to test with so I'd really appreciate if you could lend a hand.

Thanks!

**Comment by rsahlstrom** [comment]
This looked to be working for me. Filmstrip now works great with the private WPT instance in the profile.

**Comment by eduardoboucas** [comment]
Thanks for your help. This has been released as part of v1.1.1.
