### ISSUE TITLE
Content breakdown metrics show as 'undefined' in alert emails

### ISSUE THREAD

**Issue by rockeynebhwani** [speedtracker/speedtracker#35]
I am trying to use breakdown.image.bytes and breakdown.image.requests as metrics and I have defined performance budgets but when I receive alert email, I see it as undefined (see screenshot attached).

Feels like a bug. Can somebody please look into this? Here is link to my dashboard - https://rockeynebhwani.github.io/speedtracker/George-Blog/?period=week 

![image](https://cloud.githubusercontent.com/assets/1718757/24015947/08e7ce4e-0a82-11e7-90df-76e53ff26c2f.png)

**Comment by eduardoboucas** [comment]
Could you try now, please?

**Comment by rockeynebhwani** [comment]
Thanks for fixing. It's working fine now.
