### ISSUE TITLE
Enhancement - Add link to WebPageTest results page when hover specific data points on chart

### ISSUE THREAD

**Issue by rockeynebhwani** [speedtracker/speedtracker#36]
When you hover on a specific data point in chart, currently it shows timestamp of the test and values of key metric.

![image](https://cloud.githubusercontent.com/assets/1718757/24046088/4188e750-0b19-11e7-946b-f004cdeb1c06.png)

It will be good to add a link to webpagetest results so that users can start investigating using granular data when there is a sudden spike. We can either add a new link or just to save space, we can make timestamp a link.

If making it a link is difficult in hover, it should at least display the testid so that user can self navigate by typing www.webpagetest.org/result/170317_YP_2M5B (Where 170317_YP_2M5B  is an example test id)

**Comment by eduardoboucas** [comment]
I think this is useful, but I imagine that the vast majority of SpeedTracker users are using the public WebPageTest instance where test results are only held for 30 days. How would we handle this? I'm not keen on adding links that will break, which can confuse people.

**Comment by rockeynebhwani** [comment]
So, in that case we can have this test results available for only 30 days for free users and for anybody using private instance, we can have test results it linked forever.

**Comment by eduardoboucas** [comment]
I don't think this is going to work. When you hover on the data point it shows you the tooltip, but if you move the mouse to try and click on something inside the tooltip it disappears. This is how [Chart.js](http://www.chartjs.org/) works and I don't think there's a way to customise this behaviour.

Does that make sense?

**Comment by rockeynebhwani** [comment]
Hi @eduardoboucas,

I understand. Can we at least show the test ID within tooltip on hover so we know which test to look for in webpagestest in case we need to dig deeper?

Rockey

**Comment by eduardoboucas** [comment]
@rockeynebhwani This was added in [1.1.0](https://github.com/speedtracker/speedtracker/releases/tag/1.1.0). Can you update your dashboard and let me know if it works?

Thanks.

**Comment by eduardoboucas** [comment]
Released [1.1.1](https://github.com/speedtracker/speedtracker/releases/tag/1.1.1), with a label below each chart explaining what happens when you click on a data point.

**Comment by eduardoboucas** [comment]
Added in 1.1.1.
