### ISSUE TITLE
Add data from Google Lighthouse

### ISSUE THREAD

**Issue by rockeynebhwani** [speedtracker/speedtracker#44]
Hi @eduardoboucas,

You recently added graph for Google page speed. Any plans to add LightHouse score ?

Lighthouse has API now - http://help.lighthouseapp.com/kb/api

Rockey

**Comment by eduardoboucas** [comment]
I looked into it, but I don't think it's possible to run Lighthouse on a Heroku instance, since it depends on actually running a normal instance of Chrome.

**Comment by eduardoboucas** [comment]
(And you meant [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) and not lighthouseapp.com, right?)

**Comment by rockeynebhwani** [comment]
Apologies.. yes.. I meant Google Lighthouse

**Comment by eduardoboucas** [comment]
Turns out this is possible after all, since WebPageTest offers integration with Lighthouse on a few selected locations. See here: https://demo.speedtracker.org/

**Comment by rockeynebhwani** [comment]
Thanks @eduardoboucas. This looks good. I think we can close this now.
