### ISSUE TITLE
Support PerfCascade

### ISSUE THREAD

**Issue by staabm** [speedtracker/speedtracker#45]
Would be great to incorporate https://github.com/micmro/PerfCascade into the dashboard

**Comment by eduardoboucas** [comment]
The main purpose of the dashboard is to show how performance metrics progress over time, which wouldn't work with a waterfall view. Also, that information is available on the WebPageTest report, which this tool isn't trying to replace. 

Thanks for the suggestion, though!

**Comment by rockeynebhwani** [comment]
I agree that a simple waterfall view is not needed in speedtracker as it's already available on webpagetest. 

However, if were to look from visualization point of view, guys at speedcurve has improved the waterfall but making certain tweaks which they have described here -

https://speedcurve.com/blog/speedcurve-waterfall/

My favorite is using "height of each bar reflects the size of the content". It makes it very easy to spot assets with relatively high size within waterfall.

**Comment by eduardoboucas** [comment]
That's indeed a very nice touch, but it's not something we have the resources to build. SpeedCurve is a much more comprehensive solution and always will be.
