### ISSUE TITLE
Add CI Integration

### ISSUE THREAD

**Issue by ghost** [speedtracker/speedtracker#56]
Leverage CI to automate stuff. Given this repo is open source this can be accomplished in a secure way for free using Travis, reduce friction for repetitious tasks (e.g. changelog generation, deployments, version updates) and, perhaps more importantly, helps mitigate risk of human error.

**Comment by ghost** [comment]
@eduardoboucas looking for feedback here when you get around to it. I'm not sure how much of this system you want to open up. but keys can be encrypted using the travis CLI tool.

**Comment by eduardoboucas** [comment]
I'd love to see this happening! +1 for Travis.

**Comment by ghost** [comment]
Awesome. Here's an example Travis file to model from for an existing Jekyll site:

https://github.com/jhabdas/habd.as/blob/master/.travis.yml

It's [using a `Rakefile`](https://github.com/jhabdas/habd.as/blob/master/Rakefile.rb#L111-L117), though that's not necessary for regular Jekyll builds to GH. That particular site is hosted on an S3 bucket behind CloudFront for HTTPS/2.

Please let me know how I can help.

**Comment by eduardoboucas** [comment]
Here's what I do every time I release a new version of the dashboard:

- Update the version in `package.json`
- Update the version in the README file
- Create a new GitHub tag/release

How much (if any) of this do you think could be automated by the CI tool?

**Comment by ghost** [comment]
> How much (if any) of this do you think could be automated by the CI tool?

Everything except the version in the README, which could be replaced with a `CHANGELOG.md` and automatically generated with standardization of commit messages.

If you want that level of automation it's not difficult. There are a few different ways to go about it, two of which I have experience with:

**[Semantic Release](https://github.com/semantic-release/semantic-release)**

- Designed for packages.
- Highly opinionated.
- Batteries not included.
- Extreme automation.
- CHANGELOG kept in GitHub versions page.
- Requires published package (sets `0.0.0-dev` version in repo, always)

Example implementation (see manifest and click `versions` to view changelog):
https://github.com/jhabdas/fetch-inject/

Personal thoughts:
Carries so much automation you may find yourself up late at night trying to figure out how to back of something which went wrong. Viewing CHANGELOG requires an internet connection.

**[Standard Version](https://github.com/conventional-changelog/standard-version)**

- Designed for just about anything.
- Not as opinionated.
- Easy to use.
- Good enough automation.
- CHANGELOG kept in source code (necessitating version bump commits, automated).
- Does not require published NPM package (modifies manifest when generating changelog)

Example implementation:
https://github.com/comfusion/after-dark

Personal thoughts:
If Goldilocks were here she'd probably say this porridge was just about the right temperature.

**Comment by ghost** [comment]
Adding to more options, neither of which require conventional commits AFAIK:

https://github.com/zeit/release or https://github.com/egoist/changelog.md

@egoist is the creator of hackcss

**Comment by ghost** [comment]
Sorry I dropped the ball on this! I may loop back after I finish moving my creative work off GH as SpeedTracker is still the best free way I've seen to monitor metrics.
