### ISSUE TITLE
Encrypted URLs Break PageSpeed External Link

### ISSUE THREAD

**Issue by ghost** [speedtracker/speedtracker#59]
https://github.com/speedtracker/speedtracker-api/pull/23 introduced support for encrypted URLs in profile configs, which I feel is stellar. However, the UI feature which allows one to deep link to reports like PageSpeed interprets the encrypted URL literally and attempts to re-run metrics against the encrypted URL as shown here:

![screen shot 2017-04-15 at 1 27 05 pm](https://cloud.githubusercontent.com/assets/440298/25061091/d4a8cbc6-21e0-11e7-9a83-5a84147a652d.png)

Client version: https://github.com/speedtracker/speedtracker/releases/tag/1.2.2

**Comment by eduardoboucas** [comment]
This is a tricky one, as the dashboard can't decrypt any URLs. Something similar happens with the `wptUrl` property. When that's encrypted, we can't display the filmstrip view (see [here](https://github.com/speedtracker/speedtracker/blob/master/app/Dashboard.js#L125)). I think this just needs to be acknowledged and documented: when using encrypted URLs, links to PageSpeed can't work.

**Comment by ghost** [comment]
I absolutely adore the feature, and could see [envelope encryption](https://technologyadvice.github.io/lock-up-your-customer-accounts-give-away-the-key/) being used to deliver the secret to the UI if there's ever an admin section.

Until then, could you point me to any docs you'd like updated, @eduardoboucas, and offer me your thoughts on running a RegExp in the UI to look for TLD before offering _activatible_ targets (Idea here is to keep everything discoverable, but obviously suppressed for security, and hinting to the user why or why not they can/can't take action)?

This might be an opportune time to consider a backwards compatible way to work in `wpt_url` Re: naming conventions in #58.

**Comment by eduardoboucas** [comment]
At the moment, we're simply hiding the filmstrip view altogether when the URL is encrypted (we don't use a RegExp, just check to see whether the string starts with `http`). The only place this is documented is in [the default profile](https://github.com/speedtracker/speedtracker/blob/master/_profiles/default.html#L33-L39). Perhaps it should be documented somewhere in the [documentation page](https://speedtracker.org/docs)? I feel that page needs some TLC anyway.

As for hinting the user why they can't take action, not sure what's the best way to do that. Perhaps in the label that sits below the chart where we explain that they can click on a data point to view the page, we can explain that they COULD do that if their URL wasn't encrypted?

Re. changing `wptUrl` to `wpt_url`, I'm all for consistency, but I'd really like to avoid changing things here. Even if we keep accepting `wptUrl` for backwards-compatibility (until when?), it still means a potential merge conflict when people update their dashboards by just issuing a PR from the base to their fork via GitHub UI. For example, at some point I wanted to change the default SpeedIndex budget but ended up reverting for this reason.

**Comment by ghost** [comment]
Will close after digesting your thoughts, @eduardoboucas. I have an engagement coming up later this week I'm prepping for, but I won't let this stagnate too long. Cheers.

**Comment by ghost** [comment]
> At the moment, we're simply hiding the filmstrip view altogether when the URL is encrypted [...].

You sure about that? Just about every site I'm encrypting has a filmstrip view, e.g. 

http://speed.habd.as/habd_as-cable/?period=month (shows filmstrip)
https://github.com/jhabdas/speedtracker/blob/master/_profiles/habd_as-cable.html#L31 (shows profile is encrypted)

Let me know and I'll open another issue.

> As for hinting the user why they can't take action, not sure what's the best way to do that.

Tooltip. Simply replace the text and hint where the existing text lives when URL is encrypted.

> Re. changing wptUrl to wpt_url, I'm all for consistency, but I'd really like to avoid changing things here

Fair enough. It's really just a matter of rebasing properly, which I understand isn't the easiest thing for people to wrap their heads around.
