### ISSUE TITLE
Inaccurate Google Pagespeed results

### ISSUE THREAD

**Issue by TxHawks** [speedtracker/speedtracker#60]
The dashboard shows numbers between 46 and 54, however, when I click one of the data points, the rank is around 70.

**Comment by TxHawks** [comment]
My mistake. I guess the Pagespeed score shown is the desktop one rather than the mobile one. Is there a way to chose which one is shown for each profile?

**Comment by ghost** [comment]
@TxHawks it's good form to close your issues when they're resolved. Please close this, and open a separate issue if you spot a bug or want to make an enhancement proposal once you've thought it through.
