### ISSUE TITLE
Deep linking to historical reports

### ISSUE THREAD

**Issue by ghost** [speedtracker/speedtracker#61]
The ability to deep link to graph states currently is supurb, enabling users to deep link to cuts of data segmented by day, week and month. Given some users may not track using intervals (e.g. for [research purposes](https://hackernoon.com/putting-wordpress-into-hyperdrive-4705450dffc2)) it would be useful to provide the ability to either:

- Ability to deep link to a specific date range, or;
- Ability to freeze time when deep linking to a segment of data taken in the past

Without it users may drop into a deep link which is not timeless and become confused as to why they are not seeing data, as exemplified here:

http://speed.habd.as/wordcamp_habd_as-cable/?period=week

**Comment by eduardoboucas** [comment]
This makes sense. I don't know if I have the capacity to look into this anytime soon, though :/

**Comment by ghost** [comment]
> I don't know if I have the capacity to look into this anytime soon, though :/

You and I both. I'll close this for now to help keep the repo clean. Please feel free to reopen and tag if it you want to flag help from the community.
