### ISSUE TITLE
Is it broken? Or did I not set it up right?

### ISSUE THREAD

**Issue by nigelbeauty** [speedtracker/speedtracker#74]
https://nigelbeauty.github.io/speedtracker/

I thought it passed the tests and was set up fine but it's been over 8 hours and nothing has shown up yet.

**Comment by pothi** [comment]
Looks like it's been fixed. I can see the data on yours. Why don't you consider closing this ticket?

**Comment by nigelbeauty** [comment]
I will close it but I added two more profiles and they need to be set up too?

**Comment by pothi** [comment]
Correct.
